services:
  fhir:
    container_name: fhir-server
    image: ghcr.io/nhsdigital/validation-service-fhir-r4:latest
    ports:
      - "8080:8080"
    environment:
      ONTO_AUTH_URL: ${ONTO_AUTH_URL}
      ONTO_SERVER_URL: ${ONTO_SERVER_URL}
      ONTO_CLIENT_ID: ${ONTO_CLIENT_ID}
      ONTO_CLIENT_SECRET: ${ONTO_CLIENT_SECRET}
      hapi_fhir_custom_bean_packages: com.nhs
    volumes:
      - ./hapi.application.yaml:/app/config/application.yaml:ro
